### ISSUE TITLE
Enhance an existing scenario : purge-partitions

### ISSUE THREAD

**Issue by HakumenNC** [adriens/katacoda-scenarios#10]
# Context

What happens if we create a partition with a different name but a same range of an existing one?
And in case of an overlaps?

# Target scenario

You target scenario is : `purge-partitions`

# Details

Partition management behaviour

**Comment by adriens** [comment]
i'm going to add a case where wo partitions are intersecting each others.

Ina more advanced topic, I could implement parition managemnt (fusion, , ...)

**Comment by adriens** [comment]
Done in GLIA-LABS https://www.katacoda.com/glialabs/courses/postgresql/purge-partitions
Step 4 :

![image](https://user-images.githubusercontent.com/5235127/108976659-d9dd3380-76db-11eb-8f2c-badb968a91ac.png)
